config/routes.rb
Rails.application.routes.draw do
  resources :users

  root 'home#index'
  resources :tweets

  get '/login' => 'session#new_login'
  post '/login' => 'session#login'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  validates :title, presence: true
  validates :text, presence: true, length: { maximum: 170 }
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tweets

  validates_presence_of :name, :email, :password
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # GET /homes
  # GET /homes.json
  def index
  end
  
end

app/controllers/session_controller.rb
class SessionController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def new
    @user = User.first
  end

  def login(user_params)
    User.findby(email: user_params[:email])
    session[:logged_in_user_id] = user.id
    # session = {:logged_in_user_id => user.id}
    session[:message] = "Login Successful"
  end

  def logout
    session[:message] = "Logout Successful"
    session.delete :logged_in_user_id
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def show
    @tweet = Tweet.find(params[:id])
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def index
   @tweets = Tweet.all
  end

  def new
  end

  def create
  @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to @tweet
    else
      render 'new'
    end
  end

  def update
    @tweet = Tweet.find(params[:id])

    if @tweet.update(tweet_params)
      redirect_to @tweet
    else
      render 'edit'
    end
  end

  def destroy
  @tweet = Tweet.find(params[:id])
  @tweet.destroy

  redirect_to tweets_path
  end

  private

  def tweet_params
    params.require(:tweet).permit(:title,:text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    if session[:logged_in_user_id]
      User.find(session[:logged_in_user_id])
    else
      nil
    end
  end

end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Hello, Tweeters!</h1>
<%= link_to 'Current Tweets', controller: 'tweets' %>
<%= link_to 'Create a Tweet', new_tweet_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tweeter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/session/new_login.html.erb
<% redirect_to tweets_path if current_user %>

<%= form_for @user do |f| %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= form_for @tweet, url: tweet_path(@tweet), method: :patch do |f| %>

  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@tweet.errors.count, "error") %> prohibited
        this tweet from being saved:
      </h2>
      <ul>
        <% @tweet.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit 'Save Changes'%>
  </p>

<% end %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>Listing Tweets</h1>
<BR>
<%= link_to 'Create a Tweet', new_tweet_path %>
<BR>
<BR>
<table>
  <tr>
    <th>Subject</th>
    <th>Tweet</th>
    <th>Timestamp</th>
  </tr>

  <% @tweets.each do |tweet| %>
    <tr>
      <td><%= tweet.title %></td>
      <td><%= tweet.text %></td>
      <td><%= tweet.created_at %></td>
      <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
      <td><%= link_to 'Delete', tweet_path(tweet),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
    </tr>
  <% end %>
</table>

app/views/tweets/new.html.erb
<%= form_for :tweet, url: tweets_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<h1>Tweets:</h1>
<p>
  <strong>Title:</strong>
  <%= @tweet.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @tweet.text %>
</p>

<p>
  <strong>Date:</strong>
  <%= @tweet.created_at %>
</p>


<%= link_to 'Back', tweets_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>